language: python
python:
- '2.7'
- '3.6'
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
install:
- ".travis/install.sh"
script:
- ".travis/script.sh"
after_success:
- ".travis/after_success.sh"
env:
  global:
    secure: dkFZ+U8uHJTYQkvm2/IfAwNAhRTKuXc7z7tJLSMofRRFeOUM/SpLVHdDvocn+JpgwA2iSMjYVPg6g0tJJtp88X8z6cgWILCSLTp8UKVZ11vqZL/f7Tq3Dedr92PkO5oJiyt3A9L2zjEar9Ta+FQMPczqtmNBs4/Wz3d2NHhOfjdyZTLUY3fIuAgl+E8cpqenkjnBtyREG54BtHhYrIo9KrMfEwxrrDfs7oP6yol7YWVsQPeIuyl0e5Z9Q7TRkw5UclNQqRN1Vgm9XSAcYPRij1MvFWTjP7C3FCjiqYWC3bHwKy9vC0wdWaGu0mpxJ4S3YeH2NBLDRTW5J4gCwTi2Wm449VD4GzrJqzc+Qo3veLS5sEL/IfO6BxO9O1pp+NWroVVSlzZtkY35+apoLN0dipaZ7wQcEkA1/mb2zFc9g0Nh9LnZwDrNnpfu5qbFYdt+QFecUciWtWYj/Yr7kLPhpDHmxordOiCvM/3+yaJUAePAStkFJ+ZWGGJJID3N45qzlWTmDwBMCmIgiDxuC9fgQBI0YckyYs1XTcjMM3jU0dtSTMqs/McLzhCxo4SOPYEa1ujmVdS11Wk4ByKeQYPZL2XxFssACqhsa7AXhh6t7zKCF7gfSfQWkEaK1bhk39FFurEQ6e3cdBAVizDvknZ810Ed5czZD1dygwnSP9P+lW0=
